// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzYDa818NBTPsUgYDD9hMlyg4veee194',
    appId: '1:995252850202:web:1eacbd2080fc393d218ba3',
    messagingSenderId: '995252850202',
    projectId: 'glassy-storm-423606-h7',
    authDomain: 'glassy-storm-423606-h7.firebaseapp.com',
    storageBucket: 'glassy-storm-423606-h7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49wiGKvVAK1gNWtlmj0FX2P2FEmPwctA',
    appId: '1:995252850202:android:dfb2c6a29443b5e7218ba3',
    messagingSenderId: '995252850202',
    projectId: 'glassy-storm-423606-h7',
    storageBucket: 'glassy-storm-423606-h7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVS-pLuJjWOlmfgJAcTLjPjYPpXOL8BkM',
    appId: '1:995252850202:ios:ff67253f1c1e5706218ba3',
    messagingSenderId: '995252850202',
    projectId: 'glassy-storm-423606-h7',
    storageBucket: 'glassy-storm-423606-h7.appspot.com',
    iosBundleId: 'com.example.thongbaoday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVS-pLuJjWOlmfgJAcTLjPjYPpXOL8BkM',
    appId: '1:995252850202:ios:ff67253f1c1e5706218ba3',
    messagingSenderId: '995252850202',
    projectId: 'glassy-storm-423606-h7',
    storageBucket: 'glassy-storm-423606-h7.appspot.com',
    iosBundleId: 'com.example.thongbaoday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzYDa818NBTPsUgYDD9hMlyg4veee194',
    appId: '1:995252850202:web:92303160516aab9b218ba3',
    messagingSenderId: '995252850202',
    projectId: 'glassy-storm-423606-h7',
    authDomain: 'glassy-storm-423606-h7.firebaseapp.com',
    storageBucket: 'glassy-storm-423606-h7.appspot.com',
  );
}
